extends: default

ignore: |
  .build/**
  dist/**
  node_modules/**

rules:
  document-start: disable
  line-length: disable
  truthy:
    check-keys: false
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 1
  indentation:
    spaces: 2
    indent-sequences: consistent
